name = 'Sto'
license = 'MIT'
licenselink = 'https://github.com/YoursSto/yourssto.github.io/blob/main/LICENSE'
description = 'ʚɞ Theme'

# If you have a running demo of the theme
demosite = 'https://yourssto.github.io/'

# Taxonomy terms
tags = ['blog', 'personal']
features = ['some', 'awesome', 'features']


# If the theme has a single author
[author]
  name = 'YoursSto'
  homepage = 'https://linktr.ee/yourssto'