name = 'Sto'
license = 'MIT'
licenselink = 'https://github.com/YoursSto/yourssto.github.io/blob/main/LICENSE'
description = 'ʚɞ Theme'

# If you have a running demo of the theme
demosite = 'https://example.github.io/'

# Taxonomy terms
tags = ['blog', 'personal']
features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'Name of author', homepage = 'Website of author'},
  {name = 'Name of author', homepage = 'Website of author'}
]

# If the theme has a single author
[author]
  name = 'YoursSto'
  homepage = 'https://linktr.ee/yourssto'

# If porting an existing theme
[original]
  author = 'Name of original author'
  homepage = 'Website of original author'
  repo = 'https://github.com/owner/repo'
